In [10]:
"""
This is just a quick script that is able to load the files. Just using pandas can be tricky because of the newline characters in the text data. Here it is handled via the `parse_col` method.
"""

import ast
import os

import pandas as pd

our_dataset_path = 'data/'

posts_path = os.path.join(our_dataset_path, 'posts.csv')
fact_checks_path = os.path.join(our_dataset_path, 'fact_checks.csv')
fact_check_post_mapping_path = os.path.join(our_dataset_path, 'pairs.csv')

In [14]:

for path in [posts_path, fact_checks_path, fact_check_post_mapping_path]:
    assert os.path.isfile(path)

# We need to apply t = t.replace('\n', '\\n') for text fields before using `ast.literal_eval`.
# `ast.literal_eval` has problems when there are new lines in the text, e.g.:
# `ast.literal_eval('("\n")')` effectively tries to interpret the following code:

# ```
# ("
# ")
# ```

# This raises a SyntaxError exception. By escaping new lines we are able to force it to interpret it properly. There might
# be some other way to do this more systematically, but it is a workable fix for now.

parse_col = lambda s: ast.literal_eval(s.replace('\n', '\\n')) if s else s

df_fact_checks = pd.read_csv(fact_checks_path).fillna('').set_index('fact_check_id')
for col in ['claim', 'instances', 'title']:
    df_fact_checks[col] = df_fact_checks[col].apply(parse_col)


df_posts = pd.read_csv(posts_path).fillna('').set_index('post_id')
for col in ['instances', 'ocr', 'verdicts', 'text']:
    df_posts[col] = df_posts[col].apply(parse_col)


df_fact_check_post_mapping = pd.read_csv(fact_check_post_mapping_path)

In [16]:
df_fact_checks

,claim,instances,title
fact_check_id,,,
0,"( Are avocados good for you?, Are avocados go...","[(1525653998.0, https://metafact.io/factchecks...",
1,"( Can animals have headaches?, Can animals ha...","[(1617955634.0, https://metafact.io/factchecks...",
2,"( Can we help prevent Alzheimer's with diet?, ...","[(1525653998.0, https://metafact.io/factchecks...",
3,( Do any benefits of alcohol outweigh the risk...,"[(1525653998.0, https://metafact.io/factchecks...",
4,"( Does acupuncture work for headaches?, Does ...","[(1617955595.0, https://metafact.io/factchecks...",
...,...,...,...
205744,(🇫🇷 في فرنسا ، يقرر رجال الشرطة العسكرية والمد...,"[(1617976680.0, https://factuel.afp.com/ar/Fre...",(هذا الفيديو ليس لتحرّك الشرطة الفرنسيّة ضدّ ا...
205745,(👆This little beautiful girl was seen in Manga...,"[(1576281540.0, https://youturn.in/articles/ch...",(மங்களூரில் பிச்சை எடுக்கும் குழுவில் மீட்கப்ப...
205747,(📌إيطاليين و أجانب رجال و نساء ، أطفال و عجزة ...,"[(1616693700.0, https://factuel.afp.com/ar/thi...",(هذه الصور لطابورٍ أمام مركز توزيع مساعدات غذا...
205749,(🔵Confirmado... Amanhã acabarão as mensagens g...,"[(1570924680.0, https://www.boatos.org/tecnolo...",(WhatsApp vai cobrar 0.37 centavos por mensage...
205750,(🕋🗃ABRIMOS A CAIXA PRETA DO BNDES.........\n✅D...,"[(1574899140.0, https://projetocomprova.com.br...",(Post mistura dados verdadeiros com números in...

In [17]:
df_posts

,instances,ocr,verdicts,text
post_id,,,,
0,"[(1608571882.0, fb)]",[(! Dreister Impf-Fake von Markus Söder! Es is...,[False information],
1,"[(1586139153.0, fb)]",[(!! WARNING !! A new thing circulating now. P...,[False information],
2,"[(1610052141.0, fb), (1610072448.0, fb)]","[(""Actually, he's a damn sight better than any...",[Missing context],
3,"[(1645187790.0, ig)]","[(""Australia 50 MILLONES de dosis de ""vacuna"" ...",[False],
4,"[(1581697500.0, fb)]","[(""Bienaventurados los perseguidos por mi caus...",[],
...,...,...,...,...
28085,"[(1651921264.0, fb), (1651882168.0, fb)]",[],[Partly false information],(🧐Se separó el presidente...la constitución de...
28087,"[(1653138895.0, fb)]",[(bruising runny ed 1 e Contents of the pack a...,[Missing context],"(🧐🧐🧐, 🧐🧐🧐, [(eng, 1.0)])"
28089,"[(1657134606.0, fb)]",[],[Partly false information],"(🧬Robert Malone, inventeur de la technologie A..."
28090,"[(1646255245.0, tw)]",[(Number of Covid-19 Deaths 4500 4000 3500 300...,[],(🧵Enquanto você se distrai com a invasão da Rú...
28091,"[(None, fb)]","[(대중성과 발 전문적인 답반부터 하시면 시간방에 보십시, Popularity an...",[],"(🧿 대통령은 아바타... ""대통령님, 말문 막히시면 원론적인 답변부터 하시며 시간..."

In [18]:
df_fact_check_post_mapping

       post_id  fact_check_id
0         2228             33
1         2228          23568
2         2228         194577
3         2229             33
4         2229          23568
...        ...            ...
25738    14765         201987
25739    17076         201987
25740    18203         201987
25741    25641         201991
25742    25831         202891

[25743 rows x 2 columns]